version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    reviewers:
      - 'andron13'
    commit-message:
      prefix: 'deps'
    groups:
      production-dependencies:
        dependency-type: 'production'
      development-dependencies:
        dependency-type: 'development'
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: 'eslint'
        update-types: [ 'version-update:semver-major' ]
