import { ReactNode } from "react";

import "./tailwind.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/*<ReduxProvider>{children}</ReduxProvider>*/}
        {children}
      </body>
    </html>
  );
}
